version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "[%(levelname)s] %(asctime)s %(name)s %(module)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: standard
    filename: ./logs/bot.log
    when: midnight

root:
  level: DEBUG
  handlers: [console, file]
  propagate: no
